/* dconf-view.c generated by valac 0.18.0, the Vala compiler
 * generated from dconf-view.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <cairo.h>
#include <glib/gi18n-lib.h>


#define TYPE_KEY_VALUE_RENDERER (key_value_renderer_get_type ())
#define KEY_VALUE_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_KEY_VALUE_RENDERER, KeyValueRenderer))
#define KEY_VALUE_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_KEY_VALUE_RENDERER, KeyValueRendererClass))
#define IS_KEY_VALUE_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_KEY_VALUE_RENDERER))
#define IS_KEY_VALUE_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_KEY_VALUE_RENDERER))
#define KEY_VALUE_RENDERER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_KEY_VALUE_RENDERER, KeyValueRendererClass))

typedef struct _KeyValueRenderer KeyValueRenderer;
typedef struct _KeyValueRendererClass KeyValueRendererClass;
typedef struct _KeyValueRendererPrivate KeyValueRendererPrivate;

#define TYPE_DCONF_KEY_VIEW (dconf_key_view_get_type ())
#define DCONF_KEY_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DCONF_KEY_VIEW, DConfKeyView))
#define DCONF_KEY_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DCONF_KEY_VIEW, DConfKeyViewClass))
#define IS_DCONF_KEY_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DCONF_KEY_VIEW))
#define IS_DCONF_KEY_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DCONF_KEY_VIEW))
#define DCONF_KEY_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DCONF_KEY_VIEW, DConfKeyViewClass))

typedef struct _DConfKeyView DConfKeyView;
typedef struct _DConfKeyViewClass DConfKeyViewClass;

#define TYPE_KEY (key_get_type ())
#define KEY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_KEY, Key))
#define KEY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_KEY, KeyClass))
#define IS_KEY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_KEY))
#define IS_KEY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_KEY))
#define KEY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_KEY, KeyClass))

typedef struct _Key Key;
typedef struct _KeyClass KeyClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))
#define _g_variant_type_free0(var) ((var == NULL) ? NULL : (var = (g_variant_type_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _KeyPrivate KeyPrivate;

#define TYPE_DIRECTORY (directory_get_type ())
#define DIRECTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DIRECTORY, Directory))
#define DIRECTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DIRECTORY, DirectoryClass))
#define IS_DIRECTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DIRECTORY))
#define IS_DIRECTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DIRECTORY))
#define DIRECTORY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DIRECTORY, DirectoryClass))

typedef struct _Directory Directory;
typedef struct _DirectoryClass DirectoryClass;

#define TYPE_SCHEMA_KEY (schema_key_get_type ())
#define SCHEMA_KEY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SCHEMA_KEY, SchemaKey))
#define SCHEMA_KEY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SCHEMA_KEY, SchemaKeyClass))
#define IS_SCHEMA_KEY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SCHEMA_KEY))
#define IS_SCHEMA_KEY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SCHEMA_KEY))
#define SCHEMA_KEY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SCHEMA_KEY, SchemaKeyClass))

typedef struct _SchemaKey SchemaKey;
typedef struct _SchemaKeyClass SchemaKeyClass;
typedef struct _SchemaKeyPrivate SchemaKeyPrivate;

#define TYPE_SCHEMA (schema_get_type ())
#define SCHEMA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SCHEMA, Schema))
#define SCHEMA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SCHEMA, SchemaClass))
#define IS_SCHEMA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SCHEMA))
#define IS_SCHEMA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SCHEMA))
#define SCHEMA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SCHEMA, SchemaClass))

typedef struct _Schema Schema;
typedef struct _SchemaClass SchemaClass;

#define TYPE_SCHEMA_VALUE_RANGE (schema_value_range_get_type ())
#define SCHEMA_VALUE_RANGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SCHEMA_VALUE_RANGE, SchemaValueRange))
#define SCHEMA_VALUE_RANGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SCHEMA_VALUE_RANGE, SchemaValueRangeClass))
#define IS_SCHEMA_VALUE_RANGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SCHEMA_VALUE_RANGE))
#define IS_SCHEMA_VALUE_RANGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SCHEMA_VALUE_RANGE))
#define SCHEMA_VALUE_RANGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SCHEMA_VALUE_RANGE, SchemaValueRangeClass))

typedef struct _SchemaValueRange SchemaValueRange;
typedef struct _SchemaValueRangeClass SchemaValueRangeClass;

#define TYPE_SCHEMA_CHOICE (schema_choice_get_type ())
#define SCHEMA_CHOICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SCHEMA_CHOICE, SchemaChoice))
#define SCHEMA_CHOICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SCHEMA_CHOICE, SchemaChoiceClass))
#define IS_SCHEMA_CHOICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SCHEMA_CHOICE))
#define IS_SCHEMA_CHOICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SCHEMA_CHOICE))
#define SCHEMA_CHOICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SCHEMA_CHOICE, SchemaChoiceClass))

typedef struct _SchemaChoice SchemaChoice;
typedef struct _SchemaChoiceClass SchemaChoiceClass;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _SchemaChoicePrivate SchemaChoicePrivate;
#define _schema_choice_unref0(var) ((var == NULL) ? NULL : (var = (schema_choice_unref (var), NULL)))
typedef struct _SchemaPrivate SchemaPrivate;

#define TYPE_SCHEMA_LIST (schema_list_get_type ())
#define SCHEMA_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SCHEMA_LIST, SchemaList))
#define SCHEMA_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SCHEMA_LIST, SchemaListClass))
#define IS_SCHEMA_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SCHEMA_LIST))
#define IS_SCHEMA_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SCHEMA_LIST))
#define SCHEMA_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SCHEMA_LIST, SchemaListClass))

typedef struct _SchemaList SchemaList;
typedef struct _SchemaListClass SchemaListClass;
typedef struct _SchemaListPrivate SchemaListPrivate;

#define TYPE_SCHEMA_ENUM (schema_enum_get_type ())
#define SCHEMA_ENUM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SCHEMA_ENUM, SchemaEnum))
#define SCHEMA_ENUM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SCHEMA_ENUM, SchemaEnumClass))
#define IS_SCHEMA_ENUM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SCHEMA_ENUM))
#define IS_SCHEMA_ENUM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SCHEMA_ENUM))
#define SCHEMA_ENUM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SCHEMA_ENUM, SchemaEnumClass))

typedef struct _SchemaEnum SchemaEnum;
typedef struct _SchemaEnumClass SchemaEnumClass;

#define TYPE_SCHEMA_FLAGS (schema_flags_get_type ())
#define SCHEMA_FLAGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SCHEMA_FLAGS, SchemaFlags))
#define SCHEMA_FLAGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SCHEMA_FLAGS, SchemaFlagsClass))
#define IS_SCHEMA_FLAGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SCHEMA_FLAGS))
#define IS_SCHEMA_FLAGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SCHEMA_FLAGS))
#define SCHEMA_FLAGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SCHEMA_FLAGS, SchemaFlagsClass))

typedef struct _SchemaFlags SchemaFlags;
typedef struct _SchemaFlagsClass SchemaFlagsClass;

#define TYPE_ENUM_MODEL (enum_model_get_type ())
#define ENUM_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ENUM_MODEL, EnumModel))
#define ENUM_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ENUM_MODEL, EnumModelClass))
#define IS_ENUM_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ENUM_MODEL))
#define IS_ENUM_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ENUM_MODEL))
#define ENUM_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ENUM_MODEL, EnumModelClass))

typedef struct _EnumModel EnumModel;
typedef struct _EnumModelClass EnumModelClass;
typedef struct _SchemaValueRangePrivate SchemaValueRangePrivate;

#define TYPE_DCONF_DIR_VIEW (dconf_dir_view_get_type ())
#define DCONF_DIR_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DCONF_DIR_VIEW, DConfDirView))
#define DCONF_DIR_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DCONF_DIR_VIEW, DConfDirViewClass))
#define IS_DCONF_DIR_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DCONF_DIR_VIEW))
#define IS_DCONF_DIR_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DCONF_DIR_VIEW))
#define DCONF_DIR_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DCONF_DIR_VIEW, DConfDirViewClass))

typedef struct _DConfDirView DConfDirView;
typedef struct _DConfDirViewClass DConfDirViewClass;
typedef struct _DConfDirViewPrivate DConfDirViewPrivate;
typedef struct _DConfKeyViewPrivate DConfKeyViewPrivate;

struct _KeyValueRenderer {
	GtkCellRenderer parent_instance;
	KeyValueRendererPrivate * priv;
};

struct _KeyValueRendererClass {
	GtkCellRendererClass parent_class;
};

struct _KeyValueRendererPrivate {
	DConfKeyView* view;
	GtkCellRendererText* text_renderer;
	GtkCellRendererSpin* spin_renderer;
	GtkCellRendererToggle* toggle_renderer;
	GtkCellRendererCombo* combo_renderer;
	Key* _key;
};

struct _Key {
	GObject parent_instance;
	KeyPrivate * priv;
	Directory* parent;
	gchar* name;
	gchar* full_name;
	SchemaKey* schema;
};

struct _KeyClass {
	GObjectClass parent_class;
};

struct _SchemaKey {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SchemaKeyPrivate * priv;
	Schema* schema;
	gchar* name;
	gchar* type;
	GVariant* default_value;
	SchemaValueRange* range;
	SchemaValueRange* type_range;
	GList* choices;
	gchar* enum_name;
	gchar* summary;
	gchar* description;
	gchar* gettext_domain;
};

struct _SchemaKeyClass {
	GTypeClass parent_class;
	void (*finalize) (SchemaKey *self);
};

struct _SchemaChoice {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SchemaChoicePrivate * priv;
	gchar* name;
	GVariant* value;
};

struct _SchemaChoiceClass {
	GTypeClass parent_class;
	void (*finalize) (SchemaChoice *self);
};

struct _Schema {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SchemaPrivate * priv;
	SchemaList* list;
	gchar* id;
	gchar* path;
	GHashTable* keys;
};

struct _SchemaClass {
	GTypeClass parent_class;
	void (*finalize) (Schema *self);
};

struct _SchemaList {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SchemaListPrivate * priv;
	GList* schemas;
	GHashTable* keys;
	GHashTable* enums;
	GHashTable* flags;
};

struct _SchemaListClass {
	GTypeClass parent_class;
	void (*finalize) (SchemaList *self);
};

struct _SchemaValueRange {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SchemaValueRangePrivate * priv;
	GVariant* min;
	GVariant* max;
};

struct _SchemaValueRangeClass {
	GTypeClass parent_class;
	void (*finalize) (SchemaValueRange *self);
};

struct _DConfDirView {
	GtkTreeView parent_instance;
	DConfDirViewPrivate * priv;
};

struct _DConfDirViewClass {
	GtkTreeViewClass parent_class;
};

struct _DConfKeyView {
	GtkTreeView parent_instance;
	DConfKeyViewPrivate * priv;
};

struct _DConfKeyViewClass {
	GtkTreeViewClass parent_class;
};


static gpointer key_value_renderer_parent_class = NULL;
static gpointer dconf_dir_view_parent_class = NULL;
static gpointer dconf_key_view_parent_class = NULL;

GType key_value_renderer_get_type (void) G_GNUC_CONST;
GType dconf_key_view_get_type (void) G_GNUC_CONST;
GType key_get_type (void) G_GNUC_CONST;
#define KEY_VALUE_RENDERER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_KEY_VALUE_RENDERER, KeyValueRendererPrivate))
enum  {
	KEY_VALUE_RENDERER_DUMMY_PROPERTY,
	KEY_VALUE_RENDERER_KEY
};
static gdouble key_value_renderer_get_variant_as_double (GVariant* value);
KeyValueRenderer* key_value_renderer_new (DConfKeyView* view);
KeyValueRenderer* key_value_renderer_construct (GType object_type, DConfKeyView* view);
static void key_value_renderer_text_edited_cb (KeyValueRenderer* self, GtkCellRendererText* renderer, const gchar* path, const gchar* text);
static void _key_value_renderer_text_edited_cb_gtk_cell_renderer_text_edited (GtkCellRendererText* _sender, const gchar* path, const gchar* new_text, gpointer self);
static void key_value_renderer_spin_edited_cb (KeyValueRenderer* self, GtkCellRendererText* renderer, const gchar* path, const gchar* text);
static void _key_value_renderer_spin_edited_cb_gtk_cell_renderer_text_edited (GtkCellRendererText* _sender, const gchar* path, const gchar* new_text, gpointer self);
static void key_value_renderer_toggle_cb (KeyValueRenderer* self, GtkCellRendererToggle* renderer, const gchar* path);
static void _key_value_renderer_toggle_cb_gtk_cell_renderer_toggle_toggled (GtkCellRendererToggle* _sender, const gchar* path, gpointer self);
static void key_value_renderer_real_get_size (GtkCellRenderer* base, GtkWidget* widget, GdkRectangle* cell_area, gint* x_offset, gint* y_offset, gint* width, gint* height);
static GtkCellRenderer* key_value_renderer_get_renderer (KeyValueRenderer* self);
static void key_value_renderer_real_get_preferred_width (GtkCellRenderer* base, GtkWidget* widget, gint* minimum_size, gint* natural_size);
static void key_value_renderer_real_get_preferred_height_for_width (GtkCellRenderer* base, GtkWidget* widget, gint width, gint* minimum_height, gint* natural_height);
static void key_value_renderer_real_get_preferred_height (GtkCellRenderer* base, GtkWidget* widget, gint* minimum_size, gint* natural_size);
static void key_value_renderer_real_get_preferred_width_for_height (GtkCellRenderer* base, GtkWidget* widget, gint height, gint* minimum_width, gint* natural_width);
static void key_value_renderer_real_render (GtkCellRenderer* base, cairo_t* context, GtkWidget* widget, GdkRectangle* background_area, GdkRectangle* cell_area, GtkCellRendererState flags);
static gboolean key_value_renderer_real_activate (GtkCellRenderer* base, GdkEvent* event, GtkWidget* widget, const gchar* path, GdkRectangle* background_area, GdkRectangle* cell_area, GtkCellRendererState flags);
static GtkCellEditable* key_value_renderer_real_start_editing (GtkCellRenderer* base, GdkEvent* event, GtkWidget* widget, const gchar* path, GdkRectangle* background_area, GdkRectangle* cell_area, GtkCellRendererState flags);
static Key* key_value_renderer_get_key_from_path (KeyValueRenderer* self, const gchar* path);
GVariant* key_get_value (Key* self);
void key_set_value (Key* self, GVariant* value);
const gchar* key_get_type_string (Key* self);
Key* key_value_renderer_get_key (KeyValueRenderer* self);
void key_value_renderer_set_key (KeyValueRenderer* self, Key* value);
gboolean key_get_has_schema (Key* self);
GType directory_get_type (void) G_GNUC_CONST;
gpointer schema_key_ref (gpointer instance);
void schema_key_unref (gpointer instance);
GParamSpec* param_spec_schema_key (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_schema_key (GValue* value, gpointer v_object);
void value_take_schema_key (GValue* value, gpointer v_object);
gpointer value_get_schema_key (const GValue* value);
GType schema_key_get_type (void) G_GNUC_CONST;
gpointer schema_ref (gpointer instance);
void schema_unref (gpointer instance);
GParamSpec* param_spec_schema (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_schema (GValue* value, gpointer v_object);
void value_take_schema (GValue* value, gpointer v_object);
gpointer value_get_schema (const GValue* value);
GType schema_get_type (void) G_GNUC_CONST;
gpointer schema_value_range_ref (gpointer instance);
void schema_value_range_unref (gpointer instance);
GParamSpec* param_spec_schema_value_range (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_schema_value_range (GValue* value, gpointer v_object);
void value_take_schema_value_range (GValue* value, gpointer v_object);
gpointer value_get_schema_value_range (const GValue* value);
GType schema_value_range_get_type (void) G_GNUC_CONST;
gpointer schema_choice_ref (gpointer instance);
void schema_choice_unref (gpointer instance);
GParamSpec* param_spec_schema_choice (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_schema_choice (GValue* value, gpointer v_object);
void value_take_schema_choice (GValue* value, gpointer v_object);
gpointer value_get_schema_choice (const GValue* value);
GType schema_choice_get_type (void) G_GNUC_CONST;
gpointer schema_list_ref (gpointer instance);
void schema_list_unref (gpointer instance);
GParamSpec* param_spec_schema_list (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_schema_list (GValue* value, gpointer v_object);
void value_take_schema_list (GValue* value, gpointer v_object);
gpointer value_get_schema_list (const GValue* value);
GType schema_list_get_type (void) G_GNUC_CONST;
gpointer schema_enum_ref (gpointer instance);
void schema_enum_unref (gpointer instance);
GParamSpec* param_spec_schema_enum (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_schema_enum (GValue* value, gpointer v_object);
void value_take_schema_enum (GValue* value, gpointer v_object);
gpointer value_get_schema_enum (const GValue* value);
GType schema_enum_get_type (void) G_GNUC_CONST;
gpointer schema_flags_ref (gpointer instance);
void schema_flags_unref (gpointer instance);
GParamSpec* param_spec_schema_flags (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_schema_flags (GValue* value, gpointer v_object);
void value_take_schema_flags (GValue* value, gpointer v_object);
gpointer value_get_schema_flags (const GValue* value);
GType schema_flags_get_type (void) G_GNUC_CONST;
EnumModel* enum_model_new (SchemaEnum* schema_enum);
EnumModel* enum_model_construct (GType object_type, SchemaEnum* schema_enum);
GType enum_model_get_type (void) G_GNUC_CONST;
GVariant* key_get_min (Key* self);
GVariant* key_get_max (Key* self);
static void key_value_renderer_set_renderer (KeyValueRenderer* self, GtkCellRenderer* value);
static void key_value_renderer_finalize (GObject* obj);
static void _vala_key_value_renderer_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_key_value_renderer_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
GType dconf_dir_view_get_type (void) G_GNUC_CONST;
enum  {
	DCONF_DIR_VIEW_DUMMY_PROPERTY
};
DConfDirView* dconf_dir_view_new (void);
DConfDirView* dconf_dir_view_construct (GType object_type);
enum  {
	DCONF_KEY_VIEW_DUMMY_PROPERTY
};
DConfKeyView* dconf_key_view_new (void);
DConfKeyView* dconf_key_view_construct (GType object_type);


static gdouble key_value_renderer_get_variant_as_double (GVariant* value) {
	gdouble result = 0.0;
	GVariant* _tmp0_;
	GVariant* _tmp1_;
	GVariantClass _tmp2_ = 0;
	g_return_val_if_fail (value != NULL, 0.0);
	_tmp0_ = value;
	if (_tmp0_ == NULL) {
		result = 0.0;
		return result;
	}
	_tmp1_ = value;
	_tmp2_ = g_variant_classify (_tmp1_);
	switch (_tmp2_) {
		case G_VARIANT_CLASS_BYTE:
		{
			GVariant* _tmp3_;
			guint8 _tmp4_ = 0U;
			_tmp3_ = value;
			_tmp4_ = g_variant_get_byte (_tmp3_);
			result = (gdouble) _tmp4_;
			return result;
		}
		case G_VARIANT_CLASS_INT16:
		{
			GVariant* _tmp5_;
			gint16 _tmp6_ = 0;
			_tmp5_ = value;
			_tmp6_ = g_variant_get_int16 (_tmp5_);
			result = (gdouble) _tmp6_;
			return result;
		}
		case G_VARIANT_CLASS_UINT16:
		{
			GVariant* _tmp7_;
			guint16 _tmp8_ = 0U;
			_tmp7_ = value;
			_tmp8_ = g_variant_get_uint16 (_tmp7_);
			result = (gdouble) _tmp8_;
			return result;
		}
		case G_VARIANT_CLASS_INT32:
		{
			GVariant* _tmp9_;
			gint32 _tmp10_ = 0;
			_tmp9_ = value;
			_tmp10_ = g_variant_get_int32 (_tmp9_);
			result = (gdouble) _tmp10_;
			return result;
		}
		case G_VARIANT_CLASS_UINT32:
		{
			GVariant* _tmp11_;
			guint32 _tmp12_ = 0U;
			_tmp11_ = value;
			_tmp12_ = g_variant_get_uint32 (_tmp11_);
			result = (gdouble) _tmp12_;
			return result;
		}
		case G_VARIANT_CLASS_INT64:
		{
			GVariant* _tmp13_;
			gint64 _tmp14_ = 0LL;
			_tmp13_ = value;
			_tmp14_ = g_variant_get_int64 (_tmp13_);
			result = (gdouble) _tmp14_;
			return result;
		}
		case G_VARIANT_CLASS_UINT64:
		{
			GVariant* _tmp15_;
			guint64 _tmp16_ = 0ULL;
			_tmp15_ = value;
			_tmp16_ = g_variant_get_uint64 (_tmp15_);
			result = (gdouble) _tmp16_;
			return result;
		}
		case G_VARIANT_CLASS_DOUBLE:
		{
			GVariant* _tmp17_;
			gdouble _tmp18_ = 0.0;
			_tmp17_ = value;
			_tmp18_ = g_variant_get_double (_tmp17_);
			result = _tmp18_;
			return result;
		}
		default:
		{
			result = 0.0;
			return result;
		}
	}
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _key_value_renderer_text_edited_cb_gtk_cell_renderer_text_edited (GtkCellRendererText* _sender, const gchar* path, const gchar* new_text, gpointer self) {
	key_value_renderer_text_edited_cb (self, _sender, path, new_text);
}


static void _key_value_renderer_spin_edited_cb_gtk_cell_renderer_text_edited (GtkCellRendererText* _sender, const gchar* path, const gchar* new_text, gpointer self) {
	key_value_renderer_spin_edited_cb (self, _sender, path, new_text);
}


static void _key_value_renderer_toggle_cb_gtk_cell_renderer_toggle_toggled (GtkCellRendererToggle* _sender, const gchar* path, gpointer self) {
	key_value_renderer_toggle_cb (self, _sender, path);
}


KeyValueRenderer* key_value_renderer_construct (GType object_type, DConfKeyView* view) {
	KeyValueRenderer * self = NULL;
	DConfKeyView* _tmp0_;
	DConfKeyView* _tmp1_;
	GtkCellRendererText* _tmp2_;
	GtkCellRendererText* _tmp3_;
	GtkCellRendererText* _tmp4_;
	GtkCellRendererSpin* _tmp5_;
	GtkCellRendererSpin* _tmp6_;
	GtkCellRendererSpin* _tmp7_;
	GtkCellRendererToggle* _tmp8_;
	GtkCellRendererToggle* _tmp9_;
	GtkCellRendererToggle* _tmp10_;
	GtkCellRendererToggle* _tmp11_;
	GtkCellRendererCombo* _tmp12_;
	GtkCellRendererCombo* _tmp13_;
	GtkCellRendererCombo* _tmp14_;
	GtkCellRendererCombo* _tmp15_;
	GtkCellRendererCombo* _tmp16_;
	g_return_val_if_fail (view != NULL, NULL);
	self = (KeyValueRenderer*) g_object_new (object_type, NULL);
	_tmp0_ = view;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->view);
	self->priv->view = _tmp1_;
	_tmp2_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	g_object_ref_sink (_tmp2_);
	_g_object_unref0 (self->priv->text_renderer);
	self->priv->text_renderer = _tmp2_;
	_tmp3_ = self->priv->text_renderer;
	g_object_set (_tmp3_, "editable", TRUE, NULL);
	_tmp4_ = self->priv->text_renderer;
	g_signal_connect_object (_tmp4_, "edited", (GCallback) _key_value_renderer_text_edited_cb_gtk_cell_renderer_text_edited, self, 0);
	_tmp5_ = (GtkCellRendererSpin*) gtk_cell_renderer_spin_new ();
	g_object_ref_sink (_tmp5_);
	_g_object_unref0 (self->priv->spin_renderer);
	self->priv->spin_renderer = _tmp5_;
	_tmp6_ = self->priv->spin_renderer;
	g_object_set ((GtkCellRendererText*) _tmp6_, "editable", TRUE, NULL);
	_tmp7_ = self->priv->spin_renderer;
	g_signal_connect_object ((GtkCellRendererText*) _tmp7_, "edited", (GCallback) _key_value_renderer_spin_edited_cb_gtk_cell_renderer_text_edited, self, 0);
	_tmp8_ = (GtkCellRendererToggle*) gtk_cell_renderer_toggle_new ();
	g_object_ref_sink (_tmp8_);
	_g_object_unref0 (self->priv->toggle_renderer);
	self->priv->toggle_renderer = _tmp8_;
	_tmp9_ = self->priv->toggle_renderer;
	g_object_set ((GtkCellRenderer*) _tmp9_, "xalign", 0.f, NULL);
	_tmp10_ = self->priv->toggle_renderer;
	gtk_cell_renderer_toggle_set_activatable (_tmp10_, TRUE);
	_tmp11_ = self->priv->toggle_renderer;
	g_signal_connect_object (_tmp11_, "toggled", (GCallback) _key_value_renderer_toggle_cb_gtk_cell_renderer_toggle_toggled, self, 0);
	_tmp12_ = (GtkCellRendererCombo*) gtk_cell_renderer_combo_new ();
	g_object_ref_sink (_tmp12_);
	_g_object_unref0 (self->priv->combo_renderer);
	self->priv->combo_renderer = _tmp12_;
	_tmp13_ = self->priv->combo_renderer;
	g_object_set (_tmp13_, "has-entry", FALSE, NULL);
	_tmp14_ = self->priv->combo_renderer;
	g_object_set (_tmp14_, "text-column", 0, NULL);
	_tmp15_ = self->priv->combo_renderer;
	g_object_set ((GtkCellRendererText*) _tmp15_, "editable", TRUE, NULL);
	_tmp16_ = self->priv->combo_renderer;
	g_signal_connect_object ((GtkCellRendererText*) _tmp16_, "edited", (GCallback) _key_value_renderer_text_edited_cb_gtk_cell_renderer_text_edited, self, 0);
	return self;
}


KeyValueRenderer* key_value_renderer_new (DConfKeyView* view) {
	return key_value_renderer_construct (TYPE_KEY_VALUE_RENDERER, view);
}


static void key_value_renderer_real_get_size (GtkCellRenderer* base, GtkWidget* widget, GdkRectangle* cell_area, gint* x_offset, gint* y_offset, gint* width, gint* height) {
	KeyValueRenderer * self;
	gint _vala_x_offset = 0;
	gint _vala_y_offset = 0;
	gint _vala_width = 0;
	gint _vala_height = 0;
	GtkCellRenderer* _tmp0_;
	GtkCellRenderer* _tmp1_;
	GtkWidget* _tmp2_;
	GdkRectangle* _tmp3_;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	self = (KeyValueRenderer*) base;
	g_return_if_fail (widget != NULL);
	_tmp0_ = key_value_renderer_get_renderer (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = widget;
	_tmp3_ = cell_area;
	gtk_cell_renderer_get_size (_tmp1_, _tmp2_, _tmp3_, &_tmp4_, &_tmp5_, &_tmp6_, &_tmp7_);
	_vala_x_offset = _tmp4_;
	_vala_y_offset = _tmp5_;
	_vala_width = _tmp6_;
	_vala_height = _tmp7_;
	if (x_offset) {
		*x_offset = _vala_x_offset;
	}
	if (y_offset) {
		*y_offset = _vala_y_offset;
	}
	if (width) {
		*width = _vala_width;
	}
	if (height) {
		*height = _vala_height;
	}
}


static void key_value_renderer_real_get_preferred_width (GtkCellRenderer* base, GtkWidget* widget, gint* minimum_size, gint* natural_size) {
	KeyValueRenderer * self;
	gint _vala_minimum_size = 0;
	gint _vala_natural_size = 0;
	GtkCellRenderer* _tmp0_;
	GtkCellRenderer* _tmp1_;
	GtkWidget* _tmp2_;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	self = (KeyValueRenderer*) base;
	g_return_if_fail (widget != NULL);
	_tmp0_ = key_value_renderer_get_renderer (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = widget;
	gtk_cell_renderer_get_preferred_width (_tmp1_, _tmp2_, &_tmp3_, &_tmp4_);
	_vala_minimum_size = _tmp3_;
	_vala_natural_size = _tmp4_;
	if (minimum_size) {
		*minimum_size = _vala_minimum_size;
	}
	if (natural_size) {
		*natural_size = _vala_natural_size;
	}
}


static void key_value_renderer_real_get_preferred_height_for_width (GtkCellRenderer* base, GtkWidget* widget, gint width, gint* minimum_height, gint* natural_height) {
	KeyValueRenderer * self;
	gint _vala_minimum_height = 0;
	gint _vala_natural_height = 0;
	GtkCellRenderer* _tmp0_;
	GtkCellRenderer* _tmp1_;
	GtkWidget* _tmp2_;
	gint _tmp3_;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	self = (KeyValueRenderer*) base;
	g_return_if_fail (widget != NULL);
	_tmp0_ = key_value_renderer_get_renderer (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = widget;
	_tmp3_ = width;
	gtk_cell_renderer_get_preferred_height_for_width (_tmp1_, _tmp2_, _tmp3_, &_tmp4_, &_tmp5_);
	_vala_minimum_height = _tmp4_;
	_vala_natural_height = _tmp5_;
	if (minimum_height) {
		*minimum_height = _vala_minimum_height;
	}
	if (natural_height) {
		*natural_height = _vala_natural_height;
	}
}


static void key_value_renderer_real_get_preferred_height (GtkCellRenderer* base, GtkWidget* widget, gint* minimum_size, gint* natural_size) {
	KeyValueRenderer * self;
	gint _vala_minimum_size = 0;
	gint _vala_natural_size = 0;
	GtkCellRenderer* _tmp0_;
	GtkCellRenderer* _tmp1_;
	GtkWidget* _tmp2_;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	self = (KeyValueRenderer*) base;
	g_return_if_fail (widget != NULL);
	_tmp0_ = key_value_renderer_get_renderer (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = widget;
	gtk_cell_renderer_get_preferred_height (_tmp1_, _tmp2_, &_tmp3_, &_tmp4_);
	_vala_minimum_size = _tmp3_;
	_vala_natural_size = _tmp4_;
	if (minimum_size) {
		*minimum_size = _vala_minimum_size;
	}
	if (natural_size) {
		*natural_size = _vala_natural_size;
	}
}


static void key_value_renderer_real_get_preferred_width_for_height (GtkCellRenderer* base, GtkWidget* widget, gint height, gint* minimum_width, gint* natural_width) {
	KeyValueRenderer * self;
	gint _vala_minimum_width = 0;
	gint _vala_natural_width = 0;
	GtkCellRenderer* _tmp0_;
	GtkCellRenderer* _tmp1_;
	GtkWidget* _tmp2_;
	gint _tmp3_;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	self = (KeyValueRenderer*) base;
	g_return_if_fail (widget != NULL);
	_tmp0_ = key_value_renderer_get_renderer (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = widget;
	_tmp3_ = height;
	gtk_cell_renderer_get_preferred_width_for_height (_tmp1_, _tmp2_, _tmp3_, &_tmp4_, &_tmp5_);
	_vala_minimum_width = _tmp4_;
	_vala_natural_width = _tmp5_;
	if (minimum_width) {
		*minimum_width = _vala_minimum_width;
	}
	if (natural_width) {
		*natural_width = _vala_natural_width;
	}
}


static void key_value_renderer_real_render (GtkCellRenderer* base, cairo_t* context, GtkWidget* widget, GdkRectangle* background_area, GdkRectangle* cell_area, GtkCellRendererState flags) {
	KeyValueRenderer * self;
	GtkCellRenderer* _tmp0_;
	GtkCellRenderer* _tmp1_;
	cairo_t* _tmp2_;
	GtkWidget* _tmp3_;
	GdkRectangle _tmp4_;
	GdkRectangle _tmp5_;
	GtkCellRendererState _tmp6_;
	self = (KeyValueRenderer*) base;
	g_return_if_fail (context != NULL);
	g_return_if_fail (widget != NULL);
	g_return_if_fail (background_area != NULL);
	g_return_if_fail (cell_area != NULL);
	_tmp0_ = key_value_renderer_get_renderer (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = context;
	_tmp3_ = widget;
	_tmp4_ = *background_area;
	_tmp5_ = *cell_area;
	_tmp6_ = flags;
	gtk_cell_renderer_render (_tmp1_, _tmp2_, _tmp3_, &_tmp4_, &_tmp5_, _tmp6_);
}


static gboolean key_value_renderer_real_activate (GtkCellRenderer* base, GdkEvent* event, GtkWidget* widget, const gchar* path, GdkRectangle* background_area, GdkRectangle* cell_area, GtkCellRendererState flags) {
	KeyValueRenderer * self;
	gboolean result = FALSE;
	GtkCellRenderer* _tmp0_;
	GtkCellRenderer* _tmp1_;
	GdkEvent* _tmp2_;
	GtkWidget* _tmp3_;
	const gchar* _tmp4_;
	GdkRectangle _tmp5_;
	GdkRectangle _tmp6_;
	GtkCellRendererState _tmp7_;
	gboolean _tmp8_ = FALSE;
	self = (KeyValueRenderer*) base;
	g_return_val_if_fail (event != NULL, FALSE);
	g_return_val_if_fail (widget != NULL, FALSE);
	g_return_val_if_fail (path != NULL, FALSE);
	g_return_val_if_fail (background_area != NULL, FALSE);
	g_return_val_if_fail (cell_area != NULL, FALSE);
	_tmp0_ = key_value_renderer_get_renderer (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = event;
	_tmp3_ = widget;
	_tmp4_ = path;
	_tmp5_ = *background_area;
	_tmp6_ = *cell_area;
	_tmp7_ = flags;
	_tmp8_ = gtk_cell_renderer_activate (_tmp1_, _tmp2_, _tmp3_, _tmp4_, &_tmp5_, &_tmp6_, _tmp7_);
	result = _tmp8_;
	return result;
}


static GtkCellEditable* key_value_renderer_real_start_editing (GtkCellRenderer* base, GdkEvent* event, GtkWidget* widget, const gchar* path, GdkRectangle* background_area, GdkRectangle* cell_area, GtkCellRendererState flags) {
	KeyValueRenderer * self;
	GtkCellEditable* result = NULL;
	GtkCellRenderer* _tmp0_;
	GtkCellRenderer* _tmp1_;
	GdkEvent* _tmp2_;
	GtkWidget* _tmp3_;
	const gchar* _tmp4_;
	GdkRectangle _tmp5_;
	GdkRectangle _tmp6_;
	GtkCellRendererState _tmp7_;
	GtkCellEditable* _tmp8_ = NULL;
	self = (KeyValueRenderer*) base;
	g_return_val_if_fail (event != NULL, NULL);
	g_return_val_if_fail (widget != NULL, NULL);
	g_return_val_if_fail (path != NULL, NULL);
	g_return_val_if_fail (background_area != NULL, NULL);
	g_return_val_if_fail (cell_area != NULL, NULL);
	_tmp0_ = key_value_renderer_get_renderer (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = event;
	_tmp3_ = widget;
	_tmp4_ = path;
	_tmp5_ = *background_area;
	_tmp6_ = *cell_area;
	_tmp7_ = flags;
	_tmp8_ = gtk_cell_renderer_start_editing (_tmp1_, _tmp2_, _tmp3_, _tmp4_, &_tmp5_, &_tmp6_, _tmp7_);
	result = _tmp8_;
	return result;
}


static Key* key_value_renderer_get_key_from_path (KeyValueRenderer* self, const gchar* path) {
	Key* result = NULL;
	GtkTreeIter iter = {0};
	DConfKeyView* _tmp0_;
	GtkTreeModel* _tmp1_;
	GtkTreeModel* _tmp2_;
	const gchar* _tmp3_;
	GtkTreeIter _tmp4_ = {0};
	Key* key = NULL;
	DConfKeyView* _tmp5_;
	GtkTreeModel* _tmp6_;
	GtkTreeModel* _tmp7_;
	GtkTreeIter _tmp8_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = self->priv->view;
	_tmp1_ = gtk_tree_view_get_model ((GtkTreeView*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = path;
	gtk_tree_model_get_iter_from_string (_tmp2_, &_tmp4_, _tmp3_);
	iter = _tmp4_;
	_tmp5_ = self->priv->view;
	_tmp6_ = gtk_tree_view_get_model ((GtkTreeView*) _tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = iter;
	gtk_tree_model_get (_tmp7_, &_tmp8_, 0, &key, -1, -1);
	result = key;
	return result;
}


static void key_value_renderer_toggle_cb (KeyValueRenderer* self, GtkCellRendererToggle* renderer, const gchar* path) {
	const gchar* _tmp0_;
	Key* _tmp1_ = NULL;
	Key* key;
	GVariant* _tmp2_;
	GVariant* _tmp3_;
	gboolean _tmp4_ = FALSE;
	GVariant* _tmp5_;
	GVariant* _tmp6_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (renderer != NULL);
	g_return_if_fail (path != NULL);
	_tmp0_ = path;
	_tmp1_ = key_value_renderer_get_key_from_path (self, _tmp0_);
	key = _tmp1_;
	_tmp2_ = key_get_value (key);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_variant_get_boolean (_tmp3_);
	_tmp5_ = g_variant_new_boolean (!_tmp4_);
	g_variant_ref_sink (_tmp5_);
	_tmp6_ = _tmp5_;
	key_set_value (key, _tmp6_);
	_g_variant_unref0 (_tmp6_);
	_g_object_unref0 (key);
}


static void key_value_renderer_text_edited_cb (KeyValueRenderer* self, GtkCellRendererText* renderer, const gchar* path, const gchar* text) {
	const gchar* _tmp0_;
	Key* _tmp1_ = NULL;
	Key* key;
	gboolean _tmp2_ = FALSE;
	Key* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	gboolean _tmp9_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (renderer != NULL);
	g_return_if_fail (path != NULL);
	g_return_if_fail (text != NULL);
	_tmp0_ = path;
	_tmp1_ = key_value_renderer_get_key_from_path (self, _tmp0_);
	key = _tmp1_;
	_tmp3_ = key;
	_tmp4_ = key_get_type_string (_tmp3_);
	_tmp5_ = _tmp4_;
	if (g_strcmp0 (_tmp5_, "s") == 0) {
		_tmp2_ = TRUE;
	} else {
		Key* _tmp6_;
		const gchar* _tmp7_;
		const gchar* _tmp8_;
		_tmp6_ = key;
		_tmp7_ = key_get_type_string (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp2_ = g_strcmp0 (_tmp8_, "<enum>") == 0;
	}
	_tmp9_ = _tmp2_;
	if (_tmp9_) {
		Key* _tmp10_;
		const gchar* _tmp11_;
		GVariant* _tmp12_;
		GVariant* _tmp13_;
		_tmp10_ = key;
		_tmp11_ = text;
		_tmp12_ = g_variant_new_string (_tmp11_);
		g_variant_ref_sink (_tmp12_);
		_tmp13_ = _tmp12_;
		key_set_value (_tmp10_, _tmp13_);
		_g_variant_unref0 (_tmp13_);
	} else {
		{
			Key* _tmp14_;
			const gchar* _tmp15_;
			const gchar* _tmp16_;
			GVariantType* _tmp17_;
			GVariantType* _tmp18_;
			const gchar* _tmp19_;
			GVariant* _tmp20_ = NULL;
			GVariant* _tmp21_;
			GVariant* value;
			Key* _tmp22_;
			GVariant* _tmp23_;
			_tmp14_ = key;
			_tmp15_ = key_get_type_string (_tmp14_);
			_tmp16_ = _tmp15_;
			_tmp17_ = g_variant_type_new (_tmp16_);
			_tmp18_ = _tmp17_;
			_tmp19_ = text;
			_tmp20_ = g_variant_parse (_tmp18_, _tmp19_, NULL, NULL, &_inner_error_);
			_tmp21_ = _tmp20_;
			_g_variant_type_free0 (_tmp18_);
			value = _tmp21_;
			if (_inner_error_ != NULL) {
				if (_inner_error_->domain == G_VARIANT_PARSE_ERROR) {
					goto __catch8_g_variant_parse_error;
				}
				_g_object_unref0 (key);
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
			_tmp22_ = key;
			_tmp23_ = value;
			key_set_value (_tmp22_, _tmp23_);
			_g_variant_unref0 (value);
		}
		goto __finally8;
		__catch8_g_variant_parse_error:
		{
			GError* e = NULL;
			const gchar* _tmp24_ = NULL;
			GError* _tmp25_;
			const gchar* _tmp26_;
			GtkMessageDialog* _tmp27_;
			GtkMessageDialog* dialog;
			GtkMessageDialog* _tmp28_;
			GtkMessageDialog* _tmp29_;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp24_ = _ ("Error setting value: %s");
			_tmp25_ = e;
			_tmp26_ = _tmp25_->message;
			_tmp27_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_MODAL, GTK_MESSAGE_WARNING, GTK_BUTTONS_OK, _tmp24_, _tmp26_);
			g_object_ref_sink (_tmp27_);
			dialog = _tmp27_;
			_tmp28_ = dialog;
			gtk_dialog_run ((GtkDialog*) _tmp28_);
			_tmp29_ = dialog;
			gtk_widget_destroy ((GtkWidget*) _tmp29_);
			_g_object_unref0 (dialog);
			_g_error_free0 (e);
		}
		__finally8:
		if (_inner_error_ != NULL) {
			_g_object_unref0 (key);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	_g_object_unref0 (key);
}


static gdouble double_parse (const gchar* str) {
	gdouble result = 0.0;
	const gchar* _tmp0_;
	gdouble _tmp1_ = 0.0;
	g_return_val_if_fail (str != NULL, 0.0);
	_tmp0_ = str;
	_tmp1_ = g_ascii_strtod (_tmp0_, NULL);
	result = _tmp1_;
	return result;
}


static void key_value_renderer_spin_edited_cb (KeyValueRenderer* self, GtkCellRendererText* renderer, const gchar* path, const gchar* text) {
	const gchar* _tmp0_;
	Key* _tmp1_ = NULL;
	Key* key;
	Key* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	GQuark _tmp7_ = 0U;
	static GQuark _tmp6_label0 = 0;
	static GQuark _tmp6_label1 = 0;
	static GQuark _tmp6_label2 = 0;
	static GQuark _tmp6_label3 = 0;
	static GQuark _tmp6_label4 = 0;
	static GQuark _tmp6_label5 = 0;
	static GQuark _tmp6_label6 = 0;
	static GQuark _tmp6_label7 = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (renderer != NULL);
	g_return_if_fail (path != NULL);
	g_return_if_fail (text != NULL);
	_tmp0_ = path;
	_tmp1_ = key_value_renderer_get_key_from_path (self, _tmp0_);
	key = _tmp1_;
	_tmp2_ = key;
	_tmp3_ = key_get_type_string (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = _tmp4_;
	_tmp7_ = (NULL == _tmp5_) ? 0 : g_quark_from_string (_tmp5_);
	if (_tmp7_ == ((0 != _tmp6_label0) ? _tmp6_label0 : (_tmp6_label0 = g_quark_from_static_string ("y")))) {
		switch (0) {
			default:
			{
				Key* _tmp8_;
				const gchar* _tmp9_;
				gint _tmp10_ = 0;
				GVariant* _tmp11_;
				GVariant* _tmp12_;
				_tmp8_ = key;
				_tmp9_ = text;
				_tmp10_ = atoi (_tmp9_);
				_tmp11_ = g_variant_new_byte ((guchar) _tmp10_);
				g_variant_ref_sink (_tmp11_);
				_tmp12_ = _tmp11_;
				key_set_value (_tmp8_, _tmp12_);
				_g_variant_unref0 (_tmp12_);
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label1) ? _tmp6_label1 : (_tmp6_label1 = g_quark_from_static_string ("n")))) {
		switch (0) {
			default:
			{
				Key* _tmp13_;
				const gchar* _tmp14_;
				gint _tmp15_ = 0;
				GVariant* _tmp16_;
				GVariant* _tmp17_;
				_tmp13_ = key;
				_tmp14_ = text;
				_tmp15_ = atoi (_tmp14_);
				_tmp16_ = g_variant_new_int16 ((gint16) _tmp15_);
				g_variant_ref_sink (_tmp16_);
				_tmp17_ = _tmp16_;
				key_set_value (_tmp13_, _tmp17_);
				_g_variant_unref0 (_tmp17_);
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label2) ? _tmp6_label2 : (_tmp6_label2 = g_quark_from_static_string ("q")))) {
		switch (0) {
			default:
			{
				Key* _tmp18_;
				const gchar* _tmp19_;
				gint _tmp20_ = 0;
				GVariant* _tmp21_;
				GVariant* _tmp22_;
				_tmp18_ = key;
				_tmp19_ = text;
				_tmp20_ = atoi (_tmp19_);
				_tmp21_ = g_variant_new_uint16 ((guint16) _tmp20_);
				g_variant_ref_sink (_tmp21_);
				_tmp22_ = _tmp21_;
				key_set_value (_tmp18_, _tmp22_);
				_g_variant_unref0 (_tmp22_);
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label3) ? _tmp6_label3 : (_tmp6_label3 = g_quark_from_static_string ("i")))) {
		switch (0) {
			default:
			{
				Key* _tmp23_;
				const gchar* _tmp24_;
				gint _tmp25_ = 0;
				GVariant* _tmp26_;
				GVariant* _tmp27_;
				_tmp23_ = key;
				_tmp24_ = text;
				_tmp25_ = atoi (_tmp24_);
				_tmp26_ = g_variant_new_int32 ((gint32) _tmp25_);
				g_variant_ref_sink (_tmp26_);
				_tmp27_ = _tmp26_;
				key_set_value (_tmp23_, _tmp27_);
				_g_variant_unref0 (_tmp27_);
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label4) ? _tmp6_label4 : (_tmp6_label4 = g_quark_from_static_string ("u")))) {
		switch (0) {
			default:
			{
				Key* _tmp28_;
				const gchar* _tmp29_;
				gint _tmp30_ = 0;
				GVariant* _tmp31_;
				GVariant* _tmp32_;
				_tmp28_ = key;
				_tmp29_ = text;
				_tmp30_ = atoi (_tmp29_);
				_tmp31_ = g_variant_new_uint32 ((guint32) _tmp30_);
				g_variant_ref_sink (_tmp31_);
				_tmp32_ = _tmp31_;
				key_set_value (_tmp28_, _tmp32_);
				_g_variant_unref0 (_tmp32_);
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label5) ? _tmp6_label5 : (_tmp6_label5 = g_quark_from_static_string ("x")))) {
		switch (0) {
			default:
			{
				Key* _tmp33_;
				const gchar* _tmp34_;
				gint _tmp35_ = 0;
				GVariant* _tmp36_;
				GVariant* _tmp37_;
				_tmp33_ = key;
				_tmp34_ = text;
				_tmp35_ = atoi (_tmp34_);
				_tmp36_ = g_variant_new_int64 ((gint64) _tmp35_);
				g_variant_ref_sink (_tmp36_);
				_tmp37_ = _tmp36_;
				key_set_value (_tmp33_, _tmp37_);
				_g_variant_unref0 (_tmp37_);
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label6) ? _tmp6_label6 : (_tmp6_label6 = g_quark_from_static_string ("t")))) {
		switch (0) {
			default:
			{
				Key* _tmp38_;
				const gchar* _tmp39_;
				gint _tmp40_ = 0;
				GVariant* _tmp41_;
				GVariant* _tmp42_;
				_tmp38_ = key;
				_tmp39_ = text;
				_tmp40_ = atoi (_tmp39_);
				_tmp41_ = g_variant_new_uint64 ((guint64) _tmp40_);
				g_variant_ref_sink (_tmp41_);
				_tmp42_ = _tmp41_;
				key_set_value (_tmp38_, _tmp42_);
				_g_variant_unref0 (_tmp42_);
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label7) ? _tmp6_label7 : (_tmp6_label7 = g_quark_from_static_string ("d")))) {
		switch (0) {
			default:
			{
				Key* _tmp43_;
				const gchar* _tmp44_;
				gdouble _tmp45_ = 0.0;
				GVariant* _tmp46_;
				GVariant* _tmp47_;
				_tmp43_ = key;
				_tmp44_ = text;
				_tmp45_ = double_parse (_tmp44_);
				_tmp46_ = g_variant_new_double (_tmp45_);
				g_variant_ref_sink (_tmp46_);
				_tmp47_ = _tmp46_;
				key_set_value (_tmp43_, _tmp47_);
				_g_variant_unref0 (_tmp47_);
				break;
			}
		}
	}
	_g_object_unref0 (key);
}


Key* key_value_renderer_get_key (KeyValueRenderer* self) {
	Key* result;
	Key* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_key;
	result = _tmp0_;
	return result;
}


static gpointer _schema_choice_ref0 (gpointer self) {
	return self ? schema_choice_ref (self) : NULL;
}


void key_value_renderer_set_key (KeyValueRenderer* self, Key* value) {
	Key* _tmp0_;
	Key* _tmp1_;
	gboolean _tmp2_ = FALSE;
	Key* _tmp3_;
	Key* _tmp4_;
	gboolean _tmp5_;
	gboolean _tmp6_;
	gboolean _tmp11_;
	Key* _tmp37_;
	Key* _tmp38_;
	const gchar* _tmp39_;
	const gchar* _tmp40_;
	const gchar* _tmp41_;
	GQuark _tmp43_ = 0U;
	static GQuark _tmp42_label0 = 0;
	static GQuark _tmp42_label1 = 0;
	static GQuark _tmp42_label2 = 0;
	static GQuark _tmp42_label3 = 0;
	static GQuark _tmp42_label4 = 0;
	static GQuark _tmp42_label5 = 0;
	static GQuark _tmp42_label6 = 0;
	static GQuark _tmp42_label7 = 0;
	static GQuark _tmp42_label8 = 0;
	static GQuark _tmp42_label9 = 0;
	static GQuark _tmp42_label10 = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_key);
	self->priv->_key = _tmp1_;
	_tmp3_ = key_value_renderer_get_key (self);
	_tmp4_ = _tmp3_;
	_tmp5_ = key_get_has_schema (_tmp4_);
	_tmp6_ = _tmp5_;
	if (_tmp6_) {
		Key* _tmp7_;
		Key* _tmp8_;
		SchemaKey* _tmp9_;
		GList* _tmp10_;
		_tmp7_ = key_value_renderer_get_key (self);
		_tmp8_ = _tmp7_;
		_tmp9_ = _tmp8_->schema;
		_tmp10_ = _tmp9_->choices;
		_tmp2_ = _tmp10_ != NULL;
	} else {
		_tmp2_ = FALSE;
	}
	_tmp11_ = _tmp2_;
	if (_tmp11_) {
		GtkCellRendererCombo* _tmp12_;
		Key* _tmp13_;
		Key* _tmp14_;
		GVariant* _tmp15_;
		GVariant* _tmp16_;
		gchar* _tmp17_ = NULL;
		gchar* _tmp18_;
		GtkListStore* _tmp19_;
		GtkListStore* model;
		Key* _tmp20_;
		Key* _tmp21_;
		SchemaKey* _tmp22_;
		GList* _tmp23_;
		GtkCellRendererCombo* _tmp35_;
		GtkListStore* _tmp36_;
		_tmp12_ = self->priv->combo_renderer;
		_tmp13_ = key_value_renderer_get_key (self);
		_tmp14_ = _tmp13_;
		_tmp15_ = key_get_value (_tmp14_);
		_tmp16_ = _tmp15_;
		_tmp17_ = g_variant_print (_tmp16_, FALSE);
		_tmp18_ = _tmp17_;
		g_object_set ((GtkCellRendererText*) _tmp12_, "text", _tmp18_, NULL);
		_g_free0 (_tmp18_);
		_tmp19_ = gtk_list_store_new (2, G_TYPE_STRING, G_TYPE_STRING);
		model = _tmp19_;
		_tmp20_ = key_value_renderer_get_key (self);
		_tmp21_ = _tmp20_;
		_tmp22_ = _tmp21_->schema;
		_tmp23_ = _tmp22_->choices;
		{
			GList* choice_collection = NULL;
			GList* choice_it = NULL;
			choice_collection = _tmp23_;
			for (choice_it = choice_collection; choice_it != NULL; choice_it = choice_it->next) {
				SchemaChoice* _tmp24_;
				SchemaChoice* choice = NULL;
				_tmp24_ = _schema_choice_ref0 ((SchemaChoice*) choice_it->data);
				choice = _tmp24_;
				{
					GtkTreeIter iter = {0};
					GtkListStore* _tmp25_;
					GtkTreeIter _tmp26_ = {0};
					GtkListStore* _tmp27_;
					GtkTreeIter _tmp28_;
					SchemaChoice* _tmp29_;
					const gchar* _tmp30_;
					SchemaChoice* _tmp31_;
					GVariant* _tmp32_;
					gchar* _tmp33_ = NULL;
					gchar* _tmp34_;
					_tmp25_ = model;
					gtk_list_store_append (_tmp25_, &_tmp26_);
					iter = _tmp26_;
					_tmp27_ = model;
					_tmp28_ = iter;
					_tmp29_ = choice;
					_tmp30_ = _tmp29_->name;
					_tmp31_ = choice;
					_tmp32_ = _tmp31_->value;
					_tmp33_ = g_variant_print (_tmp32_, FALSE);
					_tmp34_ = _tmp33_;
					gtk_list_store_set (_tmp27_, &_tmp28_, 0, _tmp30_, 1, _tmp34_, -1, -1);
					_g_free0 (_tmp34_);
					_schema_choice_unref0 (choice);
				}
			}
		}
		_tmp35_ = self->priv->combo_renderer;
		_tmp36_ = model;
		g_object_set (_tmp35_, "model", (GtkTreeModel*) _tmp36_, NULL);
		g_object_set ((GtkCellRenderer*) self, "mode", GTK_CELL_RENDERER_MODE_EDITABLE, NULL);
		_g_object_unref0 (model);
		return;
	}
	_tmp37_ = key_value_renderer_get_key (self);
	_tmp38_ = _tmp37_;
	_tmp39_ = key_get_type_string (_tmp38_);
	_tmp40_ = _tmp39_;
	_tmp41_ = _tmp40_;
	_tmp43_ = (NULL == _tmp41_) ? 0 : g_quark_from_string (_tmp41_);
	if (_tmp43_ == ((0 != _tmp42_label0) ? _tmp42_label0 : (_tmp42_label0 = g_quark_from_static_string ("<enum>")))) {
		switch (0) {
			default:
			{
				GtkCellRendererCombo* _tmp44_;
				Key* _tmp45_;
				Key* _tmp46_;
				GVariant* _tmp47_;
				GVariant* _tmp48_;
				const gchar* _tmp49_ = NULL;
				GtkCellRendererCombo* _tmp50_;
				Key* _tmp51_;
				Key* _tmp52_;
				SchemaKey* _tmp53_;
				Schema* _tmp54_;
				SchemaList* _tmp55_;
				GHashTable* _tmp56_;
				Key* _tmp57_;
				Key* _tmp58_;
				SchemaKey* _tmp59_;
				const gchar* _tmp60_;
				gconstpointer _tmp61_ = NULL;
				EnumModel* _tmp62_;
				EnumModel* _tmp63_;
				_tmp44_ = self->priv->combo_renderer;
				_tmp45_ = key_value_renderer_get_key (self);
				_tmp46_ = _tmp45_;
				_tmp47_ = key_get_value (_tmp46_);
				_tmp48_ = _tmp47_;
				_tmp49_ = g_variant_get_string (_tmp48_, NULL);
				g_object_set ((GtkCellRendererText*) _tmp44_, "text", _tmp49_, NULL);
				_tmp50_ = self->priv->combo_renderer;
				_tmp51_ = key_value_renderer_get_key (self);
				_tmp52_ = _tmp51_;
				_tmp53_ = _tmp52_->schema;
				_tmp54_ = _tmp53_->schema;
				_tmp55_ = _tmp54_->list;
				_tmp56_ = _tmp55_->enums;
				_tmp57_ = key_value_renderer_get_key (self);
				_tmp58_ = _tmp57_;
				_tmp59_ = _tmp58_->schema;
				_tmp60_ = _tmp59_->enum_name;
				_tmp61_ = g_hash_table_lookup (_tmp56_, _tmp60_);
				_tmp62_ = enum_model_new ((SchemaEnum*) _tmp61_);
				_tmp63_ = _tmp62_;
				g_object_set (_tmp50_, "model", (GtkTreeModel*) _tmp63_, NULL);
				_g_object_unref0 (_tmp63_);
				g_object_set ((GtkCellRenderer*) self, "mode", GTK_CELL_RENDERER_MODE_EDITABLE, NULL);
				break;
			}
		}
	} else if (_tmp43_ == ((0 != _tmp42_label1) ? _tmp42_label1 : (_tmp42_label1 = g_quark_from_static_string ("b")))) {
		switch (0) {
			default:
			{
				GtkCellRendererToggle* _tmp64_;
				Key* _tmp65_;
				Key* _tmp66_;
				GVariant* _tmp67_;
				GVariant* _tmp68_;
				gboolean _tmp69_ = FALSE;
				_tmp64_ = self->priv->toggle_renderer;
				_tmp65_ = key_value_renderer_get_key (self);
				_tmp66_ = _tmp65_;
				_tmp67_ = key_get_value (_tmp66_);
				_tmp68_ = _tmp67_;
				_tmp69_ = g_variant_get_boolean (_tmp68_);
				gtk_cell_renderer_toggle_set_active (_tmp64_, _tmp69_);
				g_object_set ((GtkCellRenderer*) self, "mode", GTK_CELL_RENDERER_MODE_ACTIVATABLE, NULL);
				break;
			}
		}
	} else if (_tmp43_ == ((0 != _tmp42_label2) ? _tmp42_label2 : (_tmp42_label2 = g_quark_from_static_string ("s")))) {
		switch (0) {
			default:
			{
				GtkCellRendererText* _tmp70_;
				Key* _tmp71_;
				Key* _tmp72_;
				GVariant* _tmp73_;
				GVariant* _tmp74_;
				const gchar* _tmp75_ = NULL;
				_tmp70_ = self->priv->text_renderer;
				_tmp71_ = key_value_renderer_get_key (self);
				_tmp72_ = _tmp71_;
				_tmp73_ = key_get_value (_tmp72_);
				_tmp74_ = _tmp73_;
				_tmp75_ = g_variant_get_string (_tmp74_, NULL);
				g_object_set (_tmp70_, "text", _tmp75_, NULL);
				g_object_set ((GtkCellRenderer*) self, "mode", GTK_CELL_RENDERER_MODE_EDITABLE, NULL);
				break;
			}
		}
	} else if ((((((((_tmp43_ == ((0 != _tmp42_label3) ? _tmp42_label3 : (_tmp42_label3 = g_quark_from_static_string ("y")))) || (_tmp43_ == ((0 != _tmp42_label4) ? _tmp42_label4 : (_tmp42_label4 = g_quark_from_static_string ("n"))))) || (_tmp43_ == ((0 != _tmp42_label5) ? _tmp42_label5 : (_tmp42_label5 = g_quark_from_static_string ("q"))))) || (_tmp43_ == ((0 != _tmp42_label6) ? _tmp42_label6 : (_tmp42_label6 = g_quark_from_static_string ("i"))))) || (_tmp43_ == ((0 != _tmp42_label7) ? _tmp42_label7 : (_tmp42_label7 = g_quark_from_static_string ("u"))))) || (_tmp43_ == ((0 != _tmp42_label8) ? _tmp42_label8 : (_tmp42_label8 = g_quark_from_static_string ("x"))))) || (_tmp43_ == ((0 != _tmp42_label9) ? _tmp42_label9 : (_tmp42_label9 = g_quark_from_static_string ("t"))))) || (_tmp43_ == ((0 != _tmp42_label10) ? _tmp42_label10 : (_tmp42_label10 = g_quark_from_static_string ("d"))))) {
		switch (0) {
			default:
			{
				GtkCellRendererSpin* _tmp76_;
				Key* _tmp77_;
				Key* _tmp78_;
				GVariant* _tmp79_;
				GVariant* _tmp80_;
				gchar* _tmp81_ = NULL;
				gchar* _tmp82_;
				Key* _tmp83_;
				Key* _tmp84_;
				GVariant* _tmp85_;
				GVariant* _tmp86_;
				gdouble _tmp87_ = 0.0;
				gdouble v;
				gdouble min;
				gdouble max;
				gboolean _tmp88_ = FALSE;
				Key* _tmp89_;
				Key* _tmp90_;
				gboolean _tmp91_;
				gboolean _tmp92_;
				gboolean _tmp97_;
				GtkCellRendererSpin* _tmp120_;
				gdouble _tmp121_;
				gdouble _tmp122_;
				gdouble _tmp123_;
				GtkAdjustment* _tmp124_;
				GtkAdjustment* _tmp125_;
				GtkCellRendererSpin* _tmp126_;
				_tmp76_ = self->priv->spin_renderer;
				_tmp77_ = key_value_renderer_get_key (self);
				_tmp78_ = _tmp77_;
				_tmp79_ = key_get_value (_tmp78_);
				_tmp80_ = _tmp79_;
				_tmp81_ = g_variant_print (_tmp80_, FALSE);
				_tmp82_ = _tmp81_;
				g_object_set ((GtkCellRendererText*) _tmp76_, "text", _tmp82_, NULL);
				_g_free0 (_tmp82_);
				_tmp83_ = key_value_renderer_get_key (self);
				_tmp84_ = _tmp83_;
				_tmp85_ = key_get_value (_tmp84_);
				_tmp86_ = _tmp85_;
				_tmp87_ = key_value_renderer_get_variant_as_double (_tmp86_);
				v = _tmp87_;
				min = 0.0;
				max = 0.0;
				_tmp89_ = key_value_renderer_get_key (self);
				_tmp90_ = _tmp89_;
				_tmp91_ = key_get_has_schema (_tmp90_);
				_tmp92_ = _tmp91_;
				if (_tmp92_) {
					Key* _tmp93_;
					Key* _tmp94_;
					SchemaKey* _tmp95_;
					SchemaValueRange* _tmp96_;
					_tmp93_ = key_value_renderer_get_key (self);
					_tmp94_ = _tmp93_;
					_tmp95_ = _tmp94_->schema;
					_tmp96_ = _tmp95_->range;
					_tmp88_ = _tmp96_ != NULL;
				} else {
					_tmp88_ = FALSE;
				}
				_tmp97_ = _tmp88_;
				if (_tmp97_) {
					Key* _tmp98_;
					Key* _tmp99_;
					SchemaKey* _tmp100_;
					SchemaValueRange* _tmp101_;
					GVariant* _tmp102_;
					gdouble _tmp103_ = 0.0;
					Key* _tmp104_;
					Key* _tmp105_;
					SchemaKey* _tmp106_;
					SchemaValueRange* _tmp107_;
					GVariant* _tmp108_;
					gdouble _tmp109_ = 0.0;
					_tmp98_ = key_value_renderer_get_key (self);
					_tmp99_ = _tmp98_;
					_tmp100_ = _tmp99_->schema;
					_tmp101_ = _tmp100_->range;
					_tmp102_ = _tmp101_->min;
					_tmp103_ = key_value_renderer_get_variant_as_double (_tmp102_);
					min = _tmp103_;
					_tmp104_ = key_value_renderer_get_key (self);
					_tmp105_ = _tmp104_;
					_tmp106_ = _tmp105_->schema;
					_tmp107_ = _tmp106_->range;
					_tmp108_ = _tmp107_->max;
					_tmp109_ = key_value_renderer_get_variant_as_double (_tmp108_);
					max = _tmp109_;
				} else {
					Key* _tmp110_;
					Key* _tmp111_;
					GVariant* _tmp112_ = NULL;
					GVariant* _tmp113_;
					gdouble _tmp114_ = 0.0;
					Key* _tmp115_;
					Key* _tmp116_;
					GVariant* _tmp117_ = NULL;
					GVariant* _tmp118_;
					gdouble _tmp119_ = 0.0;
					_tmp110_ = key_value_renderer_get_key (self);
					_tmp111_ = _tmp110_;
					_tmp112_ = key_get_min (_tmp111_);
					_tmp113_ = _tmp112_;
					_tmp114_ = key_value_renderer_get_variant_as_double (_tmp113_);
					min = _tmp114_;
					_g_variant_unref0 (_tmp113_);
					_tmp115_ = key_value_renderer_get_key (self);
					_tmp116_ = _tmp115_;
					_tmp117_ = key_get_max (_tmp116_);
					_tmp118_ = _tmp117_;
					_tmp119_ = key_value_renderer_get_variant_as_double (_tmp118_);
					max = _tmp119_;
					_g_variant_unref0 (_tmp118_);
				}
				_tmp120_ = self->priv->spin_renderer;
				_tmp121_ = v;
				_tmp122_ = min;
				_tmp123_ = max;
				_tmp124_ = gtk_adjustment_new (_tmp121_, _tmp122_, _tmp123_, (gdouble) 1, (gdouble) 0, (gdouble) 0);
				g_object_ref_sink (_tmp124_);
				_tmp125_ = _tmp124_;
				g_object_set (_tmp120_, "adjustment", _tmp125_, NULL);
				_g_object_unref0 (_tmp125_);
				_tmp126_ = self->priv->spin_renderer;
				g_object_set (_tmp126_, "digits", (guint) 0, NULL);
				g_object_set ((GtkCellRenderer*) self, "mode", GTK_CELL_RENDERER_MODE_EDITABLE, NULL);
				break;
			}
		}
	} else {
		switch (0) {
			default:
			{
				GtkCellRendererText* _tmp127_;
				Key* _tmp128_;
				Key* _tmp129_;
				GVariant* _tmp130_;
				GVariant* _tmp131_;
				gchar* _tmp132_ = NULL;
				gchar* _tmp133_;
				_tmp127_ = self->priv->text_renderer;
				_tmp128_ = key_value_renderer_get_key (self);
				_tmp129_ = _tmp128_;
				_tmp130_ = key_get_value (_tmp129_);
				_tmp131_ = _tmp130_;
				_tmp132_ = g_variant_print (_tmp131_, FALSE);
				_tmp133_ = _tmp132_;
				g_object_set (_tmp127_, "text", _tmp133_, NULL);
				_g_free0 (_tmp133_);
				g_object_set ((GtkCellRenderer*) self, "mode", GTK_CELL_RENDERER_MODE_EDITABLE, NULL);
				break;
			}
		}
	}
	g_object_notify ((GObject *) self, "key");
}


static GtkCellRenderer* key_value_renderer_get_renderer (KeyValueRenderer* self) {
	GtkCellRenderer* result;
	gboolean _tmp0_ = FALSE;
	Key* _tmp1_;
	Key* _tmp2_;
	gboolean _tmp3_;
	gboolean _tmp4_;
	gboolean _tmp9_;
	Key* _tmp11_;
	Key* _tmp12_;
	const gchar* _tmp13_;
	const gchar* _tmp14_;
	const gchar* _tmp15_;
	GQuark _tmp17_ = 0U;
	static GQuark _tmp16_label0 = 0;
	static GQuark _tmp16_label1 = 0;
	static GQuark _tmp16_label2 = 0;
	static GQuark _tmp16_label3 = 0;
	static GQuark _tmp16_label4 = 0;
	static GQuark _tmp16_label5 = 0;
	static GQuark _tmp16_label6 = 0;
	static GQuark _tmp16_label7 = 0;
	static GQuark _tmp16_label8 = 0;
	static GQuark _tmp16_label9 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = key_value_renderer_get_key (self);
	_tmp2_ = _tmp1_;
	_tmp3_ = key_get_has_schema (_tmp2_);
	_tmp4_ = _tmp3_;
	if (_tmp4_) {
		Key* _tmp5_;
		Key* _tmp6_;
		SchemaKey* _tmp7_;
		GList* _tmp8_;
		_tmp5_ = key_value_renderer_get_key (self);
		_tmp6_ = _tmp5_;
		_tmp7_ = _tmp6_->schema;
		_tmp8_ = _tmp7_->choices;
		_tmp0_ = _tmp8_ != NULL;
	} else {
		_tmp0_ = FALSE;
	}
	_tmp9_ = _tmp0_;
	if (_tmp9_) {
		GtkCellRendererCombo* _tmp10_;
		_tmp10_ = self->priv->combo_renderer;
		result = (GtkCellRenderer*) _tmp10_;
		return result;
	}
	_tmp11_ = key_value_renderer_get_key (self);
	_tmp12_ = _tmp11_;
	_tmp13_ = key_get_type_string (_tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = _tmp14_;
	_tmp17_ = (NULL == _tmp15_) ? 0 : g_quark_from_string (_tmp15_);
	if (_tmp17_ == ((0 != _tmp16_label0) ? _tmp16_label0 : (_tmp16_label0 = g_quark_from_static_string ("<enum>")))) {
		switch (0) {
			default:
			{
				GtkCellRendererCombo* _tmp18_;
				_tmp18_ = self->priv->combo_renderer;
				result = (GtkCellRenderer*) _tmp18_;
				return result;
			}
		}
	} else if (_tmp17_ == ((0 != _tmp16_label1) ? _tmp16_label1 : (_tmp16_label1 = g_quark_from_static_string ("b")))) {
		switch (0) {
			default:
			{
				GtkCellRendererToggle* _tmp19_;
				_tmp19_ = self->priv->toggle_renderer;
				result = (GtkCellRenderer*) _tmp19_;
				return result;
			}
		}
	} else if ((((((((_tmp17_ == ((0 != _tmp16_label2) ? _tmp16_label2 : (_tmp16_label2 = g_quark_from_static_string ("y")))) || (_tmp17_ == ((0 != _tmp16_label3) ? _tmp16_label3 : (_tmp16_label3 = g_quark_from_static_string ("n"))))) || (_tmp17_ == ((0 != _tmp16_label4) ? _tmp16_label4 : (_tmp16_label4 = g_quark_from_static_string ("q"))))) || (_tmp17_ == ((0 != _tmp16_label5) ? _tmp16_label5 : (_tmp16_label5 = g_quark_from_static_string ("i"))))) || (_tmp17_ == ((0 != _tmp16_label6) ? _tmp16_label6 : (_tmp16_label6 = g_quark_from_static_string ("u"))))) || (_tmp17_ == ((0 != _tmp16_label7) ? _tmp16_label7 : (_tmp16_label7 = g_quark_from_static_string ("x"))))) || (_tmp17_ == ((0 != _tmp16_label8) ? _tmp16_label8 : (_tmp16_label8 = g_quark_from_static_string ("t"))))) || (_tmp17_ == ((0 != _tmp16_label9) ? _tmp16_label9 : (_tmp16_label9 = g_quark_from_static_string ("d"))))) {
		switch (0) {
			default:
			{
				GtkCellRendererSpin* _tmp20_;
				_tmp20_ = self->priv->spin_renderer;
				result = (GtkCellRenderer*) _tmp20_;
				return result;
			}
		}
	} else {
		switch (0) {
			default:
			{
				GtkCellRendererText* _tmp21_;
				_tmp21_ = self->priv->text_renderer;
				result = (GtkCellRenderer*) _tmp21_;
				return result;
			}
		}
	}
}


static void key_value_renderer_set_renderer (KeyValueRenderer* self, GtkCellRenderer* value) {
	g_return_if_fail (self != NULL);
}


static void key_value_renderer_class_init (KeyValueRendererClass * klass) {
	key_value_renderer_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (KeyValueRendererPrivate));
	GTK_CELL_RENDERER_CLASS (klass)->get_size = key_value_renderer_real_get_size;
	GTK_CELL_RENDERER_CLASS (klass)->get_preferred_width = key_value_renderer_real_get_preferred_width;
	GTK_CELL_RENDERER_CLASS (klass)->get_preferred_height_for_width = key_value_renderer_real_get_preferred_height_for_width;
	GTK_CELL_RENDERER_CLASS (klass)->get_preferred_height = key_value_renderer_real_get_preferred_height;
	GTK_CELL_RENDERER_CLASS (klass)->get_preferred_width_for_height = key_value_renderer_real_get_preferred_width_for_height;
	GTK_CELL_RENDERER_CLASS (klass)->render = key_value_renderer_real_render;
	GTK_CELL_RENDERER_CLASS (klass)->activate = key_value_renderer_real_activate;
	GTK_CELL_RENDERER_CLASS (klass)->start_editing = key_value_renderer_real_start_editing;
	G_OBJECT_CLASS (klass)->get_property = _vala_key_value_renderer_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_key_value_renderer_set_property;
	G_OBJECT_CLASS (klass)->finalize = key_value_renderer_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), KEY_VALUE_RENDERER_KEY, g_param_spec_object ("key", "key", "key", TYPE_KEY, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void key_value_renderer_instance_init (KeyValueRenderer * self) {
	self->priv = KEY_VALUE_RENDERER_GET_PRIVATE (self);
}


static void key_value_renderer_finalize (GObject* obj) {
	KeyValueRenderer * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_KEY_VALUE_RENDERER, KeyValueRenderer);
	_g_object_unref0 (self->priv->view);
	_g_object_unref0 (self->priv->text_renderer);
	_g_object_unref0 (self->priv->spin_renderer);
	_g_object_unref0 (self->priv->toggle_renderer);
	_g_object_unref0 (self->priv->combo_renderer);
	_g_object_unref0 (self->priv->_key);
	G_OBJECT_CLASS (key_value_renderer_parent_class)->finalize (obj);
}


GType key_value_renderer_get_type (void) {
	static volatile gsize key_value_renderer_type_id__volatile = 0;
	if (g_once_init_enter (&key_value_renderer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (KeyValueRendererClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) key_value_renderer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KeyValueRenderer), 0, (GInstanceInitFunc) key_value_renderer_instance_init, NULL };
		GType key_value_renderer_type_id;
		key_value_renderer_type_id = g_type_register_static (GTK_TYPE_CELL_RENDERER, "KeyValueRenderer", &g_define_type_info, 0);
		g_once_init_leave (&key_value_renderer_type_id__volatile, key_value_renderer_type_id);
	}
	return key_value_renderer_type_id__volatile;
}


static void _vala_key_value_renderer_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	KeyValueRenderer * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_KEY_VALUE_RENDERER, KeyValueRenderer);
	switch (property_id) {
		case KEY_VALUE_RENDERER_KEY:
		g_value_set_object (value, key_value_renderer_get_key (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_key_value_renderer_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	KeyValueRenderer * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_KEY_VALUE_RENDERER, KeyValueRenderer);
	switch (property_id) {
		case KEY_VALUE_RENDERER_KEY:
		key_value_renderer_set_key (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


DConfDirView* dconf_dir_view_construct (GType object_type) {
	DConfDirView * self = NULL;
	GtkCellRendererText* _tmp0_;
	GtkCellRendererText* _tmp1_;
	self = (DConfDirView*) g_object_new (object_type, NULL);
	gtk_tree_view_set_headers_visible ((GtkTreeView*) self, FALSE);
	_tmp0_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	g_object_ref_sink (_tmp0_);
	_tmp1_ = _tmp0_;
	gtk_tree_view_insert_column_with_attributes ((GtkTreeView*) self, -1, "Key", (GtkCellRenderer*) _tmp1_, "text", 1, NULL, NULL);
	_g_object_unref0 (_tmp1_);
	return self;
}


DConfDirView* dconf_dir_view_new (void) {
	return dconf_dir_view_construct (TYPE_DCONF_DIR_VIEW);
}


static void dconf_dir_view_class_init (DConfDirViewClass * klass) {
	dconf_dir_view_parent_class = g_type_class_peek_parent (klass);
}


static void dconf_dir_view_instance_init (DConfDirView * self) {
}


GType dconf_dir_view_get_type (void) {
	static volatile gsize dconf_dir_view_type_id__volatile = 0;
	if (g_once_init_enter (&dconf_dir_view_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DConfDirViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dconf_dir_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DConfDirView), 0, (GInstanceInitFunc) dconf_dir_view_instance_init, NULL };
		GType dconf_dir_view_type_id;
		dconf_dir_view_type_id = g_type_register_static (GTK_TYPE_TREE_VIEW, "DConfDirView", &g_define_type_info, 0);
		g_once_init_leave (&dconf_dir_view_type_id__volatile, dconf_dir_view_type_id);
	}
	return dconf_dir_view_type_id__volatile;
}


DConfKeyView* dconf_key_view_construct (GType object_type) {
	DConfKeyView * self = NULL;
	const gchar* _tmp0_ = NULL;
	GtkCellRendererText* _tmp1_;
	GtkCellRendererText* _tmp2_;
	GtkTreeViewColumn* _tmp3_;
	GtkTreeViewColumn* _tmp4_;
	GtkTreeViewColumn* column;
	const gchar* _tmp5_ = NULL;
	KeyValueRenderer* _tmp6_;
	KeyValueRenderer* _tmp7_;
	self = (DConfKeyView*) g_object_new (object_type, NULL);
	_tmp0_ = _ ("Name");
	_tmp1_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	g_object_ref_sink (_tmp1_);
	_tmp2_ = _tmp1_;
	_tmp3_ = gtk_tree_view_column_new_with_attributes (_tmp0_, (GtkCellRenderer*) _tmp2_, "text", 1, "weight", 4, NULL, NULL);
	g_object_ref_sink (_tmp3_);
	_tmp4_ = _tmp3_;
	_g_object_unref0 (_tmp2_);
	column = _tmp4_;
	gtk_tree_view_append_column ((GtkTreeView*) self, column);
	_tmp5_ = _ ("Value");
	_tmp6_ = key_value_renderer_new (self);
	g_object_ref_sink (_tmp6_);
	_tmp7_ = _tmp6_;
	gtk_tree_view_insert_column_with_attributes ((GtkTreeView*) self, -1, _tmp5_, (GtkCellRenderer*) _tmp7_, "key", 0, NULL, NULL);
	_g_object_unref0 (_tmp7_);
	_g_object_unref0 (column);
	return self;
}


DConfKeyView* dconf_key_view_new (void) {
	return dconf_key_view_construct (TYPE_DCONF_KEY_VIEW);
}


static void dconf_key_view_class_init (DConfKeyViewClass * klass) {
	dconf_key_view_parent_class = g_type_class_peek_parent (klass);
}


static void dconf_key_view_instance_init (DConfKeyView * self) {
}


GType dconf_key_view_get_type (void) {
	static volatile gsize dconf_key_view_type_id__volatile = 0;
	if (g_once_init_enter (&dconf_key_view_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DConfKeyViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dconf_key_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DConfKeyView), 0, (GInstanceInitFunc) dconf_key_view_instance_init, NULL };
		GType dconf_key_view_type_id;
		dconf_key_view_type_id = g_type_register_static (GTK_TYPE_TREE_VIEW, "DConfKeyView", &g_define_type_info, 0);
		g_once_init_leave (&dconf_key_view_type_id__volatile, dconf_key_view_type_id);
	}
	return dconf_key_view_type_id__volatile;
}



