#!/bin/bash
# This file based in part on the mkinitrafms script for the LFS LiveCD
# written by Alexander E. Patrakov and Jeremy Huntwork.

echo "Starting mkinitramfs"

copy()
{
  local file

  if [ "$2" == "lib" ]; then
    file=$(PATH=$LINUX_INSTALL_DIR/lib:$LINUX_INSTALL_DIR/usr/lib:$LINUX_INSTALL_DIR/lib64:$LINUX_INSTALL_DIR/usr/lib64 type -p $1)
  else
    file=$(PATH=$LINUX_INSTALL_DIR/bin:$LINUX_INSTALL_DIR/usr/bin:$LINUX_INSTALL_DIR/sbin:$LINUX_INSTALL_DIR/usr/sbin type -p $1)
  fi

  if [ -n $file ] ; then
    echo File=$file
    cp $file $WDIR/$2
  else
    echo "Missing required file: $1 for directory $2"
    rm -rf $WDIR
    exit 1
  fi
}

if [ -z $1 ] ; then
  INITRAMFS_FILE=initrd.img-no-kmods
else
  KERNEL_VERSION=$1
  INITRAMFS_FILE=initrd.img-$KERNEL_VERSION
fi

if [ -n "$KERNEL_VERSION" ] && [ ! -d "$INSTALL_MOD_PATH/lib/modules/$1" ] ; then
  echo "No modules directory named $1"
  exit 1
fi

printf "Creating $INITRAMFS_FILE... "

binfiles="bash cat cp dd ls mkdir mknod mount udevadm"
binfiles="$binfiles umount sed sleep ln rm uname"

sbinfiles="blkid switch_root killall5 agetty"

#Optional files and locations
for f in mdadm udevd; do
  if [ -x $LINUX_INSTALL_DIR/sbin/$f ] ; then sbinfiles="$sbinfiles $f"; fi
done

rm -rf $TOP/tmp/unsorted
touch $TOP/tmp/unsorted
unsorted=$TOP/tmp/unsorted

DATADIR=$TOP/boot/etc/kernel
INITIN=init.in

# Create a temporrary working directory
rm -rf $TOP/tmp/initrd-work
mkdir $TOP/tmp/initrd-work
WDIR=$TOP/tmp/initrd-work

echo unsorted=$unsorted
echo WDIR=$WDIR

# Create base directory structure
mkdir -p $WDIR/{bin,dev,lib,run,sbin,sys,proc}
mkdir -p $WDIR/etc/{modprobe.d,udev/rules.d}
touch $WDIR/etc/modprobe.d/modprobe.conf
ln -s lib $WDIR/lib64

# Create necessary device nodes
#mknod -m 640 $WDIR/dev/console c 5 1
#mknod -m 664 $WDIR/dev/null    c 1 3

# Install the udev configuration files
if [ -x $LINUX_INSTALL_DIR/etc/udev/udev.conf ] ; then
cp $LINUX_INSTALL_DIR/etc/udev/udev.conf $WDIR/etc/udev/udev.conf
fi

for file in $(find $LINUX_INSTALL_DIR/etc/udev/rules.d/ -type f) ; do
  cp $file $WDIR/etc/udev/rules.d
done

# Install any firmware present
if [ -x $LINUX_INSTALL_DIR/lib/firmware ] ; then
cp -a $LINUX_INSTALL_DIR/lib/firmware $WDIR/lib
fi

# Copy the RAID configureation file if present
if [ -f $LINUX_INSTALL_DIR/etc/mdadm.conf ] ; then
  cp $LINUX_INSTALL_DIR/etc/mdadm.conf $WDIR/etc
fi

# Install the init file
install -m0755 $DATADIR/$INITIN $WDIR/init

if [  -n "$KERNEL_VERSION" ] ; then
  if [ -x $LINUX_INSTALL_DIR/bin/kmod ] ; then
    binfiles="$binfiles kmod"
  else
    binfiles="$binfiles lsmod"
    sbinfiles="$sbinfiles insmod"
  fi
fi

# Install basic binaries
for f in $binfiles ; do
  ldd $LINUX_INSTALL_DIR/bin/$f | sed "s/\t//" | cut -d " " -f1 >> $unsorted
  copy $f bin
done

# Add lvm if present
if [ -x $LINUX_INSTALL_DIR/sbin/lvm ] ; then sbinfiles="$sbinfiles lvm"; fi

for f in $sbinfiles ; do
  ldd $LINUX_INSTALL_DIR/sbin/$f | sed "s/\t//" | cut -d " " -f1 >> $unsorted
  copy $f sbin
done

# Add udevd libraries if not in /sbin
if [ -x $LINUX_INSTALL_DIR/lib/udev/udevd ] ; then
  ldd $LINUX_INSTALL_DIR/lib/udev/udevd | sed "s/\t//" | cut -d " " -f1 >> $unsorted
fi

# Add module symlinks if appropriate
if [ -n "$KERNEL_VERSION" ] && [ -x $LINUX_INSTALL_DIR/bin/kmod ] ; then
  ln -s kmod $WDIR/bin/lsmod
  ln -s kmod $WDIR/bin/insmod
  ln -s kmod $WDIR/bin/modprobe
fi

# Add lvm symlinks if appropriate
if  [ -x $LINUX_INSTALL_DIR/sbin/lvm ] ; then
  ln -s lvm $WDIR/sbin/lvchange
  ln -s lvm $WDIR/sbin/lvrename
  ln -s lvm $WDIR/sbin/lvextend
  ln -s lvm $WDIR/sbin/lvcreate
  ln -s lvm $WDIR/sbin/lvdisplay
  ln -s lvm $WDIR/sbin/lvscan

  ln -s lvm $WDIR/sbin/pvchange
  ln -s lvm $WDIR/sbin/pvck
  ln -s lvm $WDIR/sbin/pvcreate
  ln -s lvm $WDIR/sbin/pvdisplay
  ln -s lvm $WDIR/sbin/pvscan

  ln -s lvm $WDIR/sbin/vgchange
  ln -s lvm $WDIR/sbin/vgcreate
  ln -s lvm $WDIR/sbin/vgscan
  ln -s lvm $WDIR/sbin/vgrename
  ln -s lvm $WDIR/sbin/vgck
fi

# Install libraries
sort $unsorted | uniq | while read library ; do
  if [ "$library" == "linux-vdso.so.1" ] ||
     [ "$library" == "linux-gate.so.1" ]; then
    continue
  fi

  copy $library lib
done

if [ -x $LINUX_INSTALL_DIR/lib/udev ] ; then
cp -a $LINUX_INSTALL_DIR/lib/udev $WDIR/lib
fi

# Install the kernel modules if requested
if [ -n "$KERNEL_VERSION" ]; then
  find                                                                        \
    $INSTALL_MOD_PATH/lib/modules/$KERNEL_VERSION/kernel/{crypto,fs,lib}                      \
    $INSTALL_MOD_PATH/lib/modules/$KERNEL_VERSION/kernel/drivers/{block,ata,md,firewire}      \
    $INSTALL_MOD_PATH/lib/modules/$KERNEL_VERSION/kernel/drivers/{scsi,message,pcmcia,virtio} \
    $INSTALL_MOD_PATH/lib/modules/$KERNEL_VERSION/kernel/drivers/usb/{host,storage}           \
     -type f 2> /dev/null | cpio --make-directories -p --quiet $WDIR
    mkdir $WDIR/lib/modules
    mkdir $WDIR/lib/modules/$KERNEL_VERSION
    cp $INSTALL_MOD_PATH/lib/modules/$KERNEL_VERSION/modules.{builtin,order}                     \
            $WDIR/lib/modules/$KERNEL_VERSION

  depmod -b $WDIR $KERNEL_VERSION
fi

( cd $WDIR ; find . | cpio -o -H newc --quiet | gzip -9 ) > $INITRAMFS_FILE
mv $INITRAMFS_FILE $INSTALL_PATH
# Remove the temporary directory and file
rm -rf $WDIR $unsorted
printf "done.\n"
