#ifndef LXNM_APPLET_IMAGES_H
#define LXNM_APPLET_IMAGES_H

#define LXNM_APPLET_IMAGES_COUNT 11
enum {
	LXNM_APPLET_IMAGE_MODEM,
	LXNM_APPLET_IMAGE_ADD,
	LXNM_APPLET_IMAGE_REPAIR,
	LXNM_APPLET_IMAGE_DISABLE,
	LXNM_APPLET_IMAGE_CONNECTED,
	LXNM_APPLET_IMAGE_DISCONNECT,
	LXNM_APPLET_IMAGE_PROBLEM,
	LXNM_APPLET_IMAGE_RECVDATA,
	LXNM_APPLET_IMAGE_TRANSDATA,
	LXNM_APPLET_IMAGE_RTBOTH,
	LXNM_APPLET_IMAGE_LOCK
} LXNMAppletImageType;

#define LXNM_APPLET_ANIMATION_COUNT 1
enum {
	LXNM_APPLET_ANIMATION_SCANNING
} LXNMAppletAnimationType;

#endif
