#!/bin/bash

# Place yourself outside of the ACL source tree.  In
# this example, the environment variable ACL_SOURCE
# is assumed to contain the absolute ACL source directory.

(cd $ACL_SOURCE; find . -type f) | while read F; do
	mkdir -p `dirname $F`
	ln -s $ACL_SOURCE/$F $F
done

