#!/bin/bash

# Place yourself outside of the NetworkManager source tree.  In
# this example, the environment variable NM_SOURCE
# is assumed to contain the absolute NetworkManager source directory.

(cd $NM_SOURCE; find . -type f) | while read F; do
	mkdir -p `dirname $F`
	ln -s $NM_SOURCE/$F $F
done

